repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args:
          [
            "--profile",
            "black",
            "--filter-files",
            "--skip",
            "research",
            "--skip",
            "scripts",
          ]
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
